apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "1.24.4"
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces

          metricsGenerator:
            enabled: true
            processor:
              service_graphs: {}
              span_metrics: {}
              local_blocks:
                filter_server_spans: false
                max_live_traces: 50000
            storage:
              path: /var/tempo/generator/wal
              remote_write:
                - url: http://prometheus-local.lgtm.svc.cluster.local:9090/api/v1/write
            traces_storage:
              path: /var/tempo/generator/traces

          overrides:
            defaults:
              metrics_generator:
                processors:
                  - service-graphs
                  - span-metrics
                  - local-blocks

        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
