apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AyubMulla/normal-work"
    path: gitops/components/namespaces/sample-app-namespace.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated: {}
