apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AyubMulla/normal-work"
    path: gitops/components/namespaces/temporal-namespace.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated: {}
