apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.21.2
        env:
        - name: DB_CA
          value: ""
        ports:
        - containerPort: 7233

---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  ports:
  - port: 7233
    targetPort: 7233
  selector:
    app: temporal
